### PR TITLE
Add Norwegian

### PR DESCRIPTION
**Pull request by edmellum**

### CODE REVIEW

**Comment by edmellum** [comment]
I see the tests are failing, but I'm having trouble figuring out the fixtures. Where is the source content in each language coming from? 😄

**Comment by mattico** [comment]
You need to find some freely-licensed norwegian text and add it to `tests/data`. Then run `test-lang.rs:write_output()` to generate the text fixture.

**Comment by edmellum** [comment]
I forgot about this for a while, but I've added a fixture based on a transcript from a recent Norwegian parliament speech. 😄

**Comment by mattico** [comment]
Thanks!

**Pull request merged**
